#pragma once
#include"Moon_Configuration.h"
//Compatible Moon Engine 1.2.5.1
#define Hash MoonHash
#define KeyState MoonKeyState
#define Music MoonMusic
#define GetColor MoonGetColor
#define TriangleDetection MoonTriangleDetection
#define RunProgram MoonRunProgram
#define TimeLoadInit MoonTimeLoadInit
#define TimeLoad MoonTimeLoad
#define FindEntity MoonFindEntity
#define CreateEntityIndex MoonCreateEntityIndex
#define CreateImage MoonCreateImage
#define DeletImage MoonDeletImage
#define MoonDeletImage MoonDeleteImage
#define CharToLPCWSTR MoonCharToLPCWSTR
#define CharToWchar MoonCharToWchar
#define WcharToChar MoonWcharToChar
#define TextFont MoonTextFont
#define ButtonInit MoonButtonInit
#define ButtonDetection MoonButtonDetection
#define ButtonSetTriggerMode MoonButtonSetTriggerMode
#define Window MoonWindow
#define RunWindow MoonRunWindow
#define ProjectInit MoonProjectInit
#define ProjectRun MoonProjectRun
#define ProjectOver MoonProjectOver
#define ProjectError MoonProjectError
#define ProjectPause MoonProjectPause
#define ProjectFunctionSwitch MoonProjectFunctionSwitch
#define ProjectFindEntityAllNumber MoonProjectFindEntityAllNumber
#define DrawingArea MoonDrawingArea
#define DrawingAreaAlpha MoonDrawingAreaAlpha
#define DrawingAreaRound MoonDrawingAreaRound
#define Pix MoonPix
#define Line MoonLine
#define Box MoonBox
#define BoxFull MoonBoxFull
#define ImageLoad MoonImageLoad
#define ImageLoadBatch MoonImageLoadBatch
#define AnimeInit MoonAnimeInit
#define AnimeRun MoonAnimeRun
#define AnimeDelete MoonAnimeDelete
#define AnimeCreate MoonAnimeCreate
#define MoonImagePlgBit MoonDrawingAreaPlgBit
#define ANIME MOON_ANIME
#define IMAGE MOON_IMAGE
#define PROJECTGOD MOON_PROJECTGOD
#define ENTITYINDEX MOON_ENTITYINDEX
#define TIMELOAD MOON_TIMELOAD
#define DOUBLEBUFFER MOON_DOUBLEBUFFER
#define MOON_DOUBLEBUFFER_SDL DOUBLEBUFFER_SDL
#define Lerp MoonLerp
#define RANGE MoonRANGE
#define SETMOUSECOORD MoonSETMOUSECOORD
#define Random MoonRandom
#define CMD MoonCMD
#define DegRad MoonDegRad
#define Error MOON_Error
#define NOTFOUND MOON_NOTFOUND
#define YES MOON_YES
#define NO MOON_NO
#define ON MOON_ON
#define OFF MOON_OFF
#define Pi MOON_Pi
#define TRANSPARENTCOLOR MOON_TRANSPARENTCOLOR
#define FUNCTIONSWITCH MOON_FUNCTIONSWITCH
#define HashFindEntity MoonHashFindEntity
#define PROJECTMODULE MOON_PROJECTMODULE
#define PROJECTSETTING MOON_PROJECTSETTING
#define MOONBUTTON MOON_BUTTON
#define OPEN_SDL MOON_OPEN_SDL
#define MoonRendererLoad MoonShaderLoad
#define MoonDrawingAreaAlpha MoonDrawAreaAlpha
#define MoonDrawingArea MoonDrawArea
#define MoonDrawAreaAlpha MoonDrawArea
#define MoonDrawingAreaRound MoonDrawAreaRound
#define MoonBoxFull MoonDrawBoxFull
#define MoonTriFull MoonDrawTriFull
#define MoonDrawingPix MoonDrawPix
#define MoonLine MoonDrawLine
#define MoonBox MoonDrawBox
#define MoonDeleteImage MoonImageDelete
#define MoonCreateImage MoonImageCreate
#define MoonRANGE MoonRange
#define MoonSETMOUSECOORD glfwSetCursorPos
